<template>
  <view class="page"><nav-bar title="试卷生成" :showBack="true" placeholder />
    <scroll-view scroll-y class="scroll">
      <view class="hero" @click="create"><view><text class="hero-title">创建新试卷</text><text class="hero-desc">从题库手动选择试题，快速完成组卷</text></view><text class="hero-arrow">›</text></view>
      <view class="section-title">选题来源</view>
      <view class="source-grid"><view v-for="item in sources" :key="item.key" class="source-card" @click="choose(item.key)"><text class="source-icon">{{ item.icon }}</text><text class="source-name">{{ item.name }}</text><text class="source-desc">{{ item.desc }}</text></view></view>
      <view class="section-title row"><text>最近编辑</text><text class="more" @click="goMine">我的试卷 ›</text></view>
      <view v-for="paper in papers" :key="paper.id" class="paper-card" @click="open(paper.id)"><view><text class="paper-name">{{ paper.name }}</text><text class="paper-meta">{{ paper.subject }} · {{ paper.questionCount || 0 }}题 · {{ paper.totalScore || 0 }}分</text></view><text class="status">{{ paper.status === 'draft' ? '草稿' : '已完成' }}</text></view>
      <view v-if="!loading && papers.length === 0" class="empty"><text>还没有试卷</text><text>点击上方创建你的第一份试卷</text></view>
    </scroll-view>
  </view>
</template>
<script>
import NavBar from '@/components/nav-bar/nav-bar.vue'; import { listPapers } from '@/api/paper.js'
export default { components:{NavBar}, data(){return{papers:[],loading:false,sources:[{key:'public',icon:'🌐',name:'共有题库',desc:'共同维护'},{key:'private',icon:'📚',name:'私有题库',desc:'我的题库'},{key:'favorite',icon:'★',name:'收藏夹',desc:'快速选题'}]}}, onShow(){this.load()}, methods:{async load(){this.loading=true;try{const r=await listPapers({status:'draft'});this.papers=r.data||[]}finally{this.loading=false}},create(){uni.navigateTo({url:'/subpackage_ai/paperInfo/paperInfo'})},choose(key){uni.navigateTo({url:`/subpackage_ai/paperInfo/paperInfo?source=${key}`})},open(id){uni.navigateTo({url:`/subpackage_ai/paperSelect/paperSelect?paperId=${id}`})},goMine(){uni.navigateTo({url:'/subpackage_ai/paperMine/paperMine'})}}}
</script>
<style scoped lang="scss">.page{min-height:100vh;background:#f5f8fc}.scroll{height:calc(100vh - 88rpx);padding:24rpx;box-sizing:border-box}.hero{padding:34rpx 30rpx;background:linear-gradient(135deg,#6d9cf8,#4e70df);border-radius:24rpx;color:#fff;display:flex;justify-content:space-between;align-items:center}.hero-title{display:block;font-size:40rpx;font-weight:700}.hero-desc{display:block;font-size:25rpx;opacity:.88;margin-top:12rpx}.hero-arrow{font-size:60rpx}.section-title{font-size:30rpx;font-weight:700;color:#24324a;margin:30rpx 4rpx 18rpx}.row{display:flex;justify-content:space-between}.more{font-size:25rpx;color:#4c77e8;font-weight:400}.source-grid{display:flex;gap:16rpx}.source-card{flex:1;background:#fff;border-radius:20rpx;padding:24rpx 12rpx;box-shadow:0 6rpx 22rpx rgba(61,94,145,.06)}.source-icon{display:block;font-size:42rpx}.source-name{display:block;color:#26354e;font-size:27rpx;font-weight:600;margin-top:12rpx}.source-desc{display:block;color:#9aa6b8;font-size:21rpx;margin-top:8rpx}.paper-card{background:#fff;border-radius:18rpx;padding:25rpx 24rpx;margin-bottom:14rpx;display:flex;justify-content:space-between;align-items:center}.paper-name{display:block;font-size:29rpx;color:#24324a}.paper-meta{display:block;color:#98a4b6;font-size:23rpx;margin-top:10rpx}.status{color:#5c82ee;font-size:23rpx}.empty{text-align:center;color:#a3adbd;padding:100rpx 0}.empty text{display:block;margin:10rpx}</style>
