RAG_STRATEGY_SPECS = {
    "naive_rag": {
        "label": "基础 RAG",
        "category": "baseline",
        "categoryLabel": "基线策略",
        "purpose": "基础 RAG：检索相关文档后直接生成回答。",
    },
    "multi_query_rag": {
        "label": "多查询改写 RAG",
        "category": "query_transform",
        "categoryLabel": "查询改写",
        "purpose": "多查询改写：从多个角度扩展用户问题后合并召回。",
    },
    "hyde": {
        "label": "HyDE 假设文档 RAG",
        "category": "query_transform",
        "categoryLabel": "查询改写",
        "purpose": "假设文档扩展：先生成假想答案/文档，再用它检索。",
    },
    "semantic_chunking": {
        "label": "语义切分",
        "category": "indexing",
        "categoryLabel": "索引构建",
        "purpose": "语义切分：按语义边界分块，减少上下文断裂。",
    },
    "parent_child": {
        "label": "父子块检索",
        "category": "indexing",
        "categoryLabel": "索引构建",
        "purpose": "父子块检索：小块召回，大块补充上下文。",
    },
    "hybrid_search": {
        "label": "混合检索",
        "category": "retrieval",
        "categoryLabel": "检索增强",
        "purpose": "混合检索：结合关键词检索和向量检索。",
    },
    "reranking": {
        "label": "召回重排",
        "category": "ranking",
        "categoryLabel": "排序优化",
        "purpose": "重排：对候选文档二次排序，提高最终上下文质量。",
    },
    "crag": {
        "label": "纠错 RAG",
        "category": "corrective",
        "categoryLabel": "纠错增强",
        "purpose": "纠错 RAG：评估召回质量，必要时改写或补检索。",
    },
    "self_rag": {
        "label": "自反思 RAG",
        "category": "corrective",
        "categoryLabel": "纠错增强",
        "purpose": "自反思 RAG：由模型判断是否需要检索、是否证据充分。",
    },
    "adaptive_rag": {
        "label": "自适应路由 RAG",
        "category": "routing",
        "categoryLabel": "策略路由",
        "purpose": "自适应 RAG：根据问题复杂度动态选择策略。",
    },
    "graph_rag": {
        "label": "图谱 RAG",
        "category": "structured_knowledge",
        "categoryLabel": "结构化知识",
        "purpose": "图谱 RAG：使用实体关系图谱辅助检索与推理。",
    },
    "text_to_sql": {
        "label": "自然语言转 SQL",
        "category": "structured_knowledge",
        "categoryLabel": "结构化知识",
        "purpose": "Text-to-SQL：将自然语言转成只读 SQL 查询结构化数据。",
    },
    "agentic_rag": {
        "label": "Agentic RAG",
        "category": "agentic",
        "categoryLabel": "智能体增强",
        "purpose": "Agentic RAG：由智能体规划检索、工具调用和生成。",
    },
    "multi_agent_rag": {
        "label": "多智能体 RAG",
        "category": "agentic",
        "categoryLabel": "智能体增强",
        "purpose": "多智能体 RAG：多个角色协作完成复杂问答。",
    },
    "multimodal_rag": {
        "label": "多模态 RAG",
        "category": "multimodal",
        "categoryLabel": "多模态",
        "purpose": "多模态 RAG：支持图片、表格、PDF 等多模态资料。",
    },
    "speculative_rag": {
        "label": "推测式 RAG",
        "category": "performance",
        "categoryLabel": "性能优化",
        "purpose": "推测式 RAG：先生成草稿，再并行验证和修订。",
    },
    "metadata_filter_rag": {
        "label": "元数据过滤 RAG",
        "category": "retrieval",
        "categoryLabel": "检索增强",
        "purpose": "元数据过滤 RAG：按知识库、来源、标签、业务场景等 metadata 先过滤候选，再进行重排，适合多知识库隔离检索。",
    },
    "contextual_compression_rag": {
        "label": "上下文压缩 RAG",
        "category": "ranking",
        "categoryLabel": "排序优化",
        "purpose": "上下文压缩 RAG：召回后抽取与问题最相关的句子，压缩长片段，减少无关上下文占用。",
    },
    "time_weighted_rag": {
        "label": "时间加权 RAG",
        "category": "ranking",
        "categoryLabel": "排序优化",
        "purpose": "时间加权 RAG：在相关性基础上提高近期文档权重，适合通知、政策、服务流程等会变化的知识。",
    },
    "knowledge_base_router_rag": {
        "label": "知识库路由 RAG",
        "category": "routing",
        "categoryLabel": "策略路由",
        "purpose": "知识库路由 RAG：根据问题和传入的 knowledgeBaseIds 选择目标知识库检索，适合跨多个知识库的精确召回测试。",
    },
}
