const assert = require('node:assert/strict')
const { readFileSync, existsSync } = require('node:fs')
const { join } = require('node:path')
const test = require('node:test')

const source = readFileSync(join(__dirname, 'map.vue'), 'utf8')
const poiSource = readFileSync(join(__dirname, '../../components/poi-detail-card/poi-detail-card.vue'), 'utf8')

test('default map load shows all places without requiring category selection', () => {
  assert.match(source, /selectedFacilityTypes:\s*\[\]/)
  assert.match(source, /const hasActiveFilter = selected\.length > 0/)
  assert.match(source, /\/api\/v1\/map-places/)
  assert.doesNotMatch(source, /if \(!this\.selectedFacilityTypes\.length\)[\s\S]{0,80}locationList = \[\]/)
  assert.match(source, /await this\.loadFacilityTypes\(\)/)
  assert.match(source, /fetchCurrentLocation\(\{ centerMap: false \}\)/)
  assert.match(source, /:enable-poi="false"/)
})

test('markers use lightweight pin icons and keep H5-safe marker payload', () => {
  assert.match(source, /pin-teaching\.png/)
  assert.match(source, /pin-canteen\.png/)
  assert.match(source, /pin-sport\.png/)
  assert.match(source, /pin-infra\.png/)
  assert.match(source, /window\.location\.origin/)
  assert.doesNotMatch(source, /\/static\/icons\/lcoal\/dingwei\.png/)
  assert.equal(existsSync(join(__dirname, '../../static/icons/map/pin-teaching.png')), true)
  assert.equal(existsSync(join(__dirname, '../../static/icons/map/pin-canteen.png')), true)
  assert.equal(existsSync(join(__dirname, '../../static/icons/map/pin-sport.png')), true)
})

test('map clusters nearby pins when zoomed out and lets user pick one', () => {
  assert.match(source, /buildCampusMarkerGroups/)
  assert.match(source, /buildClusterMarker/)
  assert.match(source, /openClusterPicker/)
  assert.match(source, /CLUSTER_SCALE_MIN = 8/)
  assert.match(source, /CLUSTER_SCALE_MAX = 16/)
  assert.match(source, /resolveClusterDistanceMeters/)
  assert.match(source, /mergeNearbyMarkerGroups/)
  assert.match(source, /groupsShouldMerge/)
  assert.match(source, /findNearestCampusGroup/)
  assert.match(source, /suppressMapTapUntil/)
  assert.match(source, /CLUSTER_ID_BASE = 800000/)
  assert.match(source, /pin-cluster-\$\{/)
  assert.match(source, /该区域/)
  assert.doesNotMatch(source, /buildClusterMarker\([\s\S]{0,260}label:/)
  assert.equal(existsSync(join(__dirname, '../../static/icons/map/pin-cluster.png')), true)
  assert.equal(existsSync(join(__dirname, '../../static/icons/map/pin-cluster-4.png')), true)
})

test('poi detail follows amap layout without phone or upload action', () => {
  assert.doesNotMatch(poiSource, /上传照片/)
  assert.match(poiSource, /walkText/)
  assert.match(poiSource, /去这里/)
  assert.match(poiSource, /\$emit\('map-click'\)/)
  assert.doesNotMatch(poiSource, /电话/)
  assert.doesNotMatch(poiSource, /补充电话/)
  assert.match(source, /@map-click="onPoiMapAction"/)
  assert.match(source, /formatWalkSummary/)
  assert.match(source, /await this\.fetchPlaceDetail\(item\.id\)/)
})

test('map keeps all fences visible and loads floor plan plus indoor points in-page', () => {
  assert.match(source, /buildAllFenceOverlays/)
  assert.match(source, /ensurePlaceFloors/)
  assert.match(source, /openFloorPanel/)
  assert.match(source, /fetchPlaceDetail/)
  assert.match(source, /includeChildren:\s*false/)
  assert.match(source, /getPlaceChildren/)
  assert.match(source, /placeDetailCache/)
  assert.match(source, /floorContentCache/)
  assert.match(source, /getFloorPlan/)
  assert.match(source, /getIndoorPositions/)
  assert.match(source, /sheetExpandLevel/)
  assert.match(source, /activePanel/)
  assert.doesNotMatch(source, /hydrateBuildingFloors/)
  assert.doesNotMatch(source, /getMarkerList/)
  assert.doesNotMatch(source, /getPlaceFence/)
  assert.doesNotMatch(source, /notice-btn-map/)
  assert.match(poiSource, /楼层平面图/)
  assert.match(poiSource, /该楼层暂未上传平面图/)
  assert.match(poiSource, /该楼层暂无室内点位/)
  assert.doesNotMatch(source, /onPoiCategoryAction[\s\S]{0,180}uni\.navigateTo/)
})

test('h5 map uses absolute static icons and native-style marker labels', () => {
  assert.doesNotMatch(source, /campus-points-dock/)
  assert.match(source, /provider="amap"/)
  assert.match(source, /:polygons="amapPolygons"/)
  assert.match(source, /category-bar/)
  assert.match(source, /bgColor: '#ffffff'/)
  assert.match(source, /assignMarkerLabelLayouts/)
  assert.doesNotMatch(source, /map-debug-banner/)
  assert.match(source, /shouldShowCampusMarkers/)
  assert.match(source, /不要设 title/)
  assert.match(source, /resolveMarkerLabelFontSize/)
  assert.match(source, /@regionchange="onRegionChange"/)
  assert.match(source, /setMapViewport/)
  assert.match(source, /mapPlacesCache/)
  assert.match(source, /手势缩放只更新聚类/)
  assert.doesNotMatch(source, /onRegionChange\([\s\S]{0,500}this\.setMapViewport/)
  assert.match(source, /mapPlacesInflight/)
  assert.match(source, /fetchEnabledMapPlaces/)
  assert.match(source, /window\.location\.origin/)
})

test('map keeps locate logic without the floating tool buttons', () => {
  assert.doesNotMatch(source, /class="map-tool-stack"/)
  assert.doesNotMatch(source, /aria-label="回到当前位置"/)
  assert.match(source, /fetchCurrentLocation\(\{ centerMap: true, showError: true \}\)/)
  assert.match(source, /uni\.createMapContext\('campusAmap', this\)/)
  assert.match(source, /mapContext\.moveToLocation\(\{ longitude, latitude \}\)/)
  assert.match(source, /无法获取当前位置，请检查定位权限/)
})

test('poi detail drops fence and updated-at, and indoor points are tappable', () => {
  assert.doesNotMatch(poiSource, /围栏/)
  assert.doesNotMatch(poiSource, /最近更新/)
  assert.match(poiSource, /poi-detail-sheet__marker/)
  assert.match(poiSource, /poi-detail-sheet__point-list/)
  assert.match(poiSource, /indoor-select/)
})

test('indoor stall detail shows the same fields as admin stall form', () => {
  assert.match(source, /locationDesc: point\.locationDesc/)
  assert.match(source, /businessHours: point\.businessHours/)
  assert.match(source, /avgPrice: point\.avgPrice/)
  assert.match(source, /stallStatus: point\.stallStatus/)
  assert.match(poiSource, /档口位置/)
  assert.match(poiSource, /营业时间/)
  assert.match(poiSource, /人均价格/)
  assert.match(poiSource, /档口介绍/)
  assert.match(poiSource, /stallStatusText/)
})
