import { request } from '../utils/request.js'

export const listPaperBanks = (params = {}) => request({ url: '/api/papers/banks', method: 'GET', data: params })
export const createPaperBank = (data) => request({ url: '/api/papers/banks', method: 'POST', data })
export const updatePaperBank = (id, data) => request({ url: `/api/papers/banks/${id}`, method: 'PUT', data })
export const deletePaperBank = (id) => request({ url: `/api/papers/banks/${id}`, method: 'DELETE' })
export const addQuestionToBank = (bankId, questionId) => request({ url: `/api/papers/banks/${bankId}/questions/${questionId}`, method: 'POST' })
export const listQuestions = (bankId, params = {}) => request({ url: `/api/papers/banks/${bankId}/questions`, method: 'GET', data: params })
export const listFavoriteQuestions = (params = {}) => request({ url: '/api/papers/favorites', method: 'GET', data: params })
export const favoriteQuestion = (id) => request({ url: `/api/papers/questions/${id}/favorite`, method: 'POST' })
export const unfavoriteQuestion = (id) => request({ url: `/api/papers/questions/${id}/favorite`, method: 'DELETE' })
export const listPapers = (params = {}) => request({ url: '/api/papers', method: 'GET', data: params })
export const createPaper = (data) => request({ url: '/api/papers', method: 'POST', data })
export const getPaper = (id) => request({ url: `/api/papers/${id}`, method: 'GET' })
export const updatePaper = (id, data) => request({ url: `/api/papers/${id}`, method: 'PUT', data })
export const addPaperQuestion = (id, data) => request({ url: `/api/papers/${id}/questions`, method: 'POST', data })
export const updatePaperQuestion = (paperId, questionId, data) => request({ url: `/api/papers/${paperId}/questions/${questionId}`, method: 'PUT', data })
export const removePaperQuestion = (paperId, questionId) => request({ url: `/api/papers/${paperId}/questions/${questionId}`, method: 'DELETE' })
export const completePaper = (id) => request({ url: `/api/papers/${id}/complete`, method: 'POST' })
export const copyPaper = (id) => request({ url: `/api/papers/${id}/copy`, method: 'POST' })
export const deletePaper = (id) => request({ url: `/api/papers/${id}`, method: 'DELETE' })
