server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: AppBackend
  sql:
    init:
      mode: always
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/smart-campus?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB

springdoc:
  api-docs:
    version: openapi_3_0
  swagger-ui:
    path: /swagger-ui.html
