<script setup>
import { ref } from 'vue'
import AppTabBar from '../components/AppTabBar.vue'
import { updateAvatar, updatePassword } from '../api/user'
import { getUserInfo, setUserInfo } from '../utils/auth'
const password=ref({oldPassword:'',newPassword:'',confirmPassword:''}),avatarUrl=ref(getUserInfo()?.avatar||''),busy=ref(''),error=ref(''),success=ref('')
async function savePassword(){if(password.value.newPassword!==password.value.confirmPassword){error.value='两次输入的新密码不一致';return}busy.value='password';error.value='';success.value='';try{await updatePassword({oldPassword:password.value.oldPassword,newPassword:password.value.newPassword});success.value='密码修改成功';password.value={oldPassword:'',newPassword:'',confirmPassword:''}}catch(cause){error.value=cause.message}finally{busy.value=''}}
async function saveAvatar(){busy.value='avatar';error.value='';success.value='';try{await updateAvatar(avatarUrl.value);const user=getUserInfo()||{};setUserInfo({...user,avatar:avatarUrl.value});success.value='头像已更新'}catch(cause){error.value=cause.message}finally{busy.value=''}}
</script>
<template><div class="feature-page"><AppTabBar/><main class="settings-page"><header class="feature-heading"><div><h1>账户设置</h1><p>管理头像和登录密码</p></div></header><div v-if="error" class="feature-error">{{error}}</div><div v-if="success" class="success">{{success}}</div><div class="feature-grid"><form class="feature-card feature-form panel" @submit.prevent="saveAvatar"><h2>头像设置</h2><div class="avatar-preview"><img v-if="avatarUrl" :src="avatarUrl" alt=""/><span v-else>头像</span></div><label>头像地址<input v-model="avatarUrl" class="feature-input" type="url" placeholder="请输入已上传图片地址"/></label><button class="feature-button feature-button--primary" :disabled="busy==='avatar'">保存头像</button></form><form class="feature-card feature-form panel" @submit.prevent="savePassword"><h2>修改密码</h2><label>当前密码<input v-model="password.oldPassword" class="feature-input" type="password" required/></label><label>新密码<input v-model="password.newPassword" class="feature-input" type="password" required minlength="6"/></label><label>确认新密码<input v-model="password.confirmPassword" class="feature-input" type="password" required minlength="6"/></label><button class="feature-button feature-button--primary" :disabled="busy==='password'">修改密码</button></form></div></main></div></template>
<style scoped>
.settings-page{width:min(900px,calc(100% - 32px));margin:auto;padding:28px 0 48px}.panel{padding:24px}.panel h2{margin-top:0}.avatar-preview{display:grid;place-items:center;width:96px;height:96px;border-radius:50%;overflow:hidden;color:#718096;background:#edf2f6}.avatar-preview img{width:100%;height:100%;object-fit:cover}.success{margin-bottom:14px;padding:12px;border:1px solid #cbe3d7;border-radius:8px;color:#39735d;background:#f1faf6}
</style>
