<script setup>
import { computed, onActivated, onBeforeUnmount, onMounted, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import AppTabBar from '../components/AppTabBar.vue'
import { answerCareerChapterQuestion, completeCareerChapter, getCareerChapter, getCareerMaterialUrl, getCareerPlanet, updateCareerVideoProgress } from '../api/careerNebula'
import { startExam } from '../api/exam'

const route = useRoute(); const router = useRouter(); const planet = ref(null); const chapterDetail = ref(null)
const props = defineProps({ careerId: { type: String, default: '' }, skillId: { type: String, default: '' }, modal: Boolean })
const emit = defineEmits(['close'])
const currentCareerId = computed(() => props.careerId || String(route.params.careerId || ''))
const currentSkillId = computed(() => props.skillId || String(route.params.skillId || ''))
const videoElement = ref(null); const loading = ref(true); const error = ref(''); const busy = ref(''); const lastHeartbeat = ref(0)
const videoFinished = ref(false); const quizMode = ref(false); const questionIndex = ref(0); const answerInput = ref(''); const answerResult = ref(null)
const restartFromBeginning = ref(false)
const progress = computed(() => Number(planet.value?.explorationProgress || 0)); const exam = computed(() => planet.value?.finalExam || {})
const watchedPercent = computed(() => chapterDetail.value?.video?.watchedPercent || 0)
let heartbeatTimer

async function load() { loading.value = true; error.value = ''; try { planet.value = await getCareerPlanet(currentCareerId.value, currentSkillId.value) } catch (e) { error.value = e.message } finally { loading.value = false } }
async function openChapter(chapter) { busy.value = `chapter-${chapter.id}`; error.value = ''; try { chapterDetail.value = await getCareerChapter(currentCareerId.value, currentSkillId.value, chapter.id); if (chapterDetail.value?.video?.materialId) { const resolved = await getCareerMaterialUrl(planet.value.courseId, chapter.id, chapterDetail.value.video.materialId); chapterDetail.value.video.url = resolved?.fileUrl || chapterDetail.value.video.url } lastHeartbeat.value = chapterDetail.value?.video?.positionSeconds || 0; videoFinished.value = Boolean(chapterDetail.value?.video?.completed); quizMode.value = false; questionIndex.value = 0; answerInput.value = ''; answerResult.value = null } catch (e) { error.value = e.message } finally { busy.value = '' } }
async function reportVideo(force = false) {
  const media = videoElement.value; const item = chapterDetail.value?.video
  if (!media || !item?.materialId || (!force && media.paused)) return
  const current = Math.floor(media.currentTime || 0); const delta = Math.max(0, Math.min(20, current - lastHeartbeat.value))
  if (!force && delta < 18) return
  lastHeartbeat.value = current
  try { chapterDetail.value.video = await updateCareerVideoProgress(currentCareerId.value, currentSkillId.value, chapterDetail.value.chapterId, { materialId: item.materialId, currentSeconds: current, durationSeconds: Math.floor(media.duration || item.durationSeconds || 0), watchedSecondsDelta: delta }) } catch (e) { error.value = e.message }
}
function videoLoaded() { if (restartFromBeginning.value) { videoElement.value.currentTime = 0; restartFromBeginning.value = false } else if (chapterDetail.value?.video?.positionSeconds) videoElement.value.currentTime = chapterDetail.value.video.positionSeconds; lastHeartbeat.value = Math.floor(videoElement.value?.currentTime || 0) }
async function videoEnded() { await reportVideo(true); videoFinished.value = true }
function replayVideo() { quizMode.value = false; videoFinished.value = false; answerResult.value = null; if (videoElement.value) { videoElement.value.currentTime = 0; lastHeartbeat.value = 0; videoElement.value.play() } }
function enterQuiz() { quizMode.value = true; answerInput.value = ''; answerResult.value = null }
async function submitAnswer() { const question = chapterDetail.value?.questions?.[questionIndex.value]; if (!question || !answerInput.value.trim()) return; busy.value = 'answer'; try { answerResult.value = await answerCareerChapterQuestion(currentCareerId.value, currentSkillId.value, chapterDetail.value.chapterId, question.id, answerInput.value); chapterDetail.value.quizCompleted = Boolean(answerResult.value?.correct) } catch (e) { error.value = e.message } finally { busy.value = '' } }
function relearn() { restartFromBeginning.value = true; quizMode.value = false; videoFinished.value = false; answerInput.value = ''; answerResult.value = null; lastHeartbeat.value = 0 }
async function finishChapter() { busy.value = 'complete'; error.value = ''; try { await reportVideo(true); planet.value = await completeCareerChapter(currentCareerId.value, currentSkillId.value, chapterDetail.value.chapterId); chapterDetail.value.chapterCompleted = true } catch (e) { error.value = e.message } finally { busy.value = '' } }
async function closeChapter() { await reportVideo(true); chapterDetail.value = null; await load() }
async function nextChapter() { if (chapterDetail.value?.nextChapterId) await openChapter({ id: chapterDetail.value.nextChapterId }) }
async function takeFinalExam() { if (!planet.value?.finalExamUnlocked || !exam.value.paperId) return; busy.value = 'exam'; try { const attempt = await startExam(exam.value.paperId); router.push({ name: 'exam-taking', params: { attemptId: attempt.id }, query: { returnCareer: currentCareerId.value, returnSkill: currentSkillId.value } }) } catch (e) { error.value = e.message } finally { busy.value = '' } }
onMounted(() => { load(); heartbeatTimer = window.setInterval(() => reportVideo(), 20000) }); onActivated(load)
onBeforeUnmount(() => { window.clearInterval(heartbeatTimer); reportVideo(true) })
</script>

<template>
  <div class="planet-page" :class="{ 'modal-page': modal }" @click.self="modal && emit('close')"><AppTabBar v-if="!modal" /><main class="planet-shell" :class="{ 'modal-shell': modal }">
    <button v-if="modal" class="modal-page-close" type="button" aria-label="关闭课程星球" @click="emit('close')">×</button>
    <button v-else class="back" type="button" @click="router.push(`/career/nebula/${currentCareerId}`)">← 返回岗位星图</button>
    <div v-if="loading" class="state">正在读取课程星球…</div><div v-else-if="error && !planet" class="state error">{{ error }}</div>
    <template v-else-if="planet">
      <header class="hero"><div><small>COURSE PLANET</small><h1>{{ planet.name }}</h1><p>{{ planet.description || '完成全部必修章节后，参加期末考试完成星球探索。' }}</p></div></header>
      <section class="progress-card"><div class="progress-head"><span>星球探索进度</span><b>{{ progress }}%</b></div><div class="track"><i :style="{ width: `${progress}%` }"></i></div><div class="progress-parts"><span>章节学习 {{ planet.chapterProgress }}/60</span><span>期末考试 {{ planet.examProgress }}/40</span></div></section>
      <p v-if="error" class="inline-error">{{ error }}</p>
      <section class="chapter-section"><h2>课程章节</h2><article v-for="(chapter, index) in planet.chapters" :key="chapter.id" class="chapter-card"><span class="number">{{ chapter.completed ? '✓' : String(index + 1).padStart(2, '0') }}</span><div><strong>{{ chapter.title }}</strong><small>{{ chapter.summary || '课程章节' }} · {{ chapter.estimatedMinutes || 0 }}分钟</small></div><em>{{ chapter.completed ? '已完成' : chapter.videoProgress ? `学习中 ${chapter.videoProgress}%` : '待探索' }}</em><button type="button" :disabled="busy === `chapter-${chapter.id}`" @click="openChapter(chapter)">{{ chapter.completed ? '复习' : chapter.videoProgress ? '继续学习' : '开始学习' }}</button></article></section>
      <section class="exam-card" :class="{ locked: !planet.finalExamUnlocked }"><div><small>FINAL EXAM · 40%</small><h2>{{ exam.title || '期末考试' }}</h2><p v-if="!planet.finalExamUnlocked">完成全部必修章节，探索进度达到60%后开放</p><p v-else-if="planet.finalExamPassed">考试已通过，课程星球探索完成</p><p v-else>共{{ exam.questionCount || 0 }}题 · {{ exam.durationMinutes || 0 }}分钟 · 60分及格</p></div><button type="button" :disabled="!planet.finalExamUnlocked || planet.finalExamPassed || busy === 'exam'" @click="takeFinalExam">{{ planet.finalExamPassed ? '已完成' : planet.finalExamUnlocked ? '参加期末考试' : '尚未解锁' }}</button></section>
    </template>
  </main>

  <div v-if="chapterDetail" class="modal-backdrop" @click.self="closeChapter"><section class="chapter-modal" role="dialog" aria-modal="true"><button class="modal-close" type="button" @click="closeChapter">×</button>
    <header class="modal-header"><small>CHAPTER LEARNING</small><h2>{{ chapterDetail.title }}</h2><p>{{ chapterDetail.summary }}</p></header>
    <div class="modal-body"><section class="video-panel">
      <div v-if="quizMode" class="quiz-panel"><small>CHAPTER QUIZ</small><h3>{{ chapterDetail.questions[questionIndex]?.question }}</h3><textarea v-model="answerInput" :disabled="Boolean(answerResult)" placeholder="请输入你的答案"></textarea><button v-if="!answerResult" :disabled="!answerInput.trim() || busy === 'answer'" @click="submitAnswer">提交答案</button><div v-else class="answer-feedback" :class="{ correct: answerResult.correct, wrong: !answerResult.correct }"><strong>{{ answerResult.correct ? '✓ 回答正确' : '× 回答错误' }}</strong><p v-if="!answerResult.correct">正确答案：{{ answerResult.correctAnswer }}</p><p>解析：{{ answerResult.explanation }}</p></div></div>
      <template v-else><video v-if="chapterDetail.video?.url" ref="videoElement" :src="chapterDetail.video.url" controls preload="metadata" @loadedmetadata="videoLoaded" @pause="reportVideo(true)" @ended="videoEnded"></video><div v-else class="video-empty"><span>当前章节未关联视频，请联系管理员在课程章节中关联已有视频资料</span></div><div v-if="videoFinished && chapterDetail.video?.url" class="video-finished"><strong>是否重新播放视频？</strong><div><button @click="replayVideo">重新播放视频</button></div></div><div class="video-progress"><span>观看进度 {{ watchedPercent }}%</span><span>有效学习 {{ Math.floor((chapterDetail.video?.effectiveWatchedSeconds || 0) / 60) }}分钟 / {{ Math.ceil((chapterDetail.video?.durationSeconds || 0) / 60) }}分钟</span></div></template>
    </section>
      <div class="reading"><section><h3>本章内容</h3><p>{{ chapterDetail.content || chapterDetail.summary || '暂无章节正文。' }}</p></section><section class="materials"><h3>学习资料</h3><a v-for="item in chapterDetail.materials" :key="item.materialId" :href="item.url" target="_blank" rel="noopener">{{ item.fileName }}<span>查看</span></a><p v-if="!chapterDetail.materials?.length">暂无附加资料</p></section></div></div>
    <p v-if="error" class="modal-error">{{ error }}</p><footer class="modal-actions"><template v-if="chapterDetail.chapterCompleted"><strong>✓ 本章探索完成</strong><button v-if="chapterDetail.nextChapterId" @click="nextChapter">学习下一章</button></template><template v-else-if="quizMode && answerResult?.correct"><strong>✓ 回答正确</strong><button :disabled="busy === 'complete'" @click="finishChapter">完成本章学习</button></template><template v-else-if="quizMode && answerResult && !answerResult.correct"><small>回答错误，请重新学习后再次作答</small><button @click="relearn">重新学习</button></template><template v-else-if="!quizMode && chapterDetail.questions?.length"><button @click="enterQuiz">进入答题</button></template><template v-else-if="!chapterDetail.questions?.length"><button :disabled="busy === 'complete'" @click="finishChapter">完成本章学习</button></template></footer>
  </section></div></div>
</template>

<style scoped>
.planet-page{min-height:100vh;color:#dcecff;background:radial-gradient(circle at 75% 15%,#102d50 0,transparent 28%),linear-gradient(155deg,#020812,#071829 55%,#020711)}.planet-shell{width:min(1100px,calc(100% - 40px));margin:auto;padding:90px 0 60px}.back{margin-bottom:20px;color:#8dcfff;background:transparent}.state{padding:80px;text-align:center}.error,.inline-error,.modal-error{color:#fca5a5}.hero,.progress-card,.chapter-card,.exam-card{border:1px solid rgba(64,174,235,.3);background:rgba(5,25,43,.82)}.hero{display:flex;align-items:center;justify-content:space-between;padding:30px}.hero small,.exam-card small,.modal-header small{color:#4fc3ff;letter-spacing:.18em}.hero h1{margin:9px 0;font-size:32px}.hero p,.modal-header p{margin:0;color:#88a7bc}.hero>strong{font-size:48px;color:#6ed0ff}.progress-card{margin-top:14px;padding:20px}.progress-head,.progress-parts,.video-progress{display:flex;justify-content:space-between}.track{height:8px;margin:14px 0;background:#102e46}.track i{display:block;height:100%;background:#39baff}.progress-parts,.video-progress{color:#789bb2;font-size:13px}.chapter-section{margin-top:30px}.chapter-card{display:grid;grid-template-columns:42px minmax(0,1fr) auto auto;align-items:center;gap:15px;margin-top:10px;padding:14px}.number{display:grid;width:36px;height:36px;place-items:center;border:1px solid #337da8;border-radius:50%;color:#58c7ff}.chapter-card div{display:grid;gap:5px}.chapter-card small,.chapter-card em{color:#789bb2;font-size:12px;font-style:normal}.chapter-card button,.exam-card button,.modal-actions button{padding:10px 17px;border:1px solid #39baff;color:#dff6ff;background:#0d527a}.exam-card{display:flex;align-items:center;justify-content:space-between;margin-top:28px;padding:24px}.exam-card h2{margin:7px 0}.exam-card p{margin:0;color:#789bb2}.exam-card.locked{opacity:.65}
.modal-page{position:fixed;z-index:85;inset:0;display:grid;min-height:0;padding:20px;place-items:center;background:rgba(0,6,14,.82);backdrop-filter:blur(7px)}.modal-page .modal-shell{position:relative;display:flex;box-sizing:border-box;width:60vw;max-width:60vw;height:60vh;max-height:60vh;margin:0;padding:38px 22px 18px;overflow-x:hidden;overflow-y:auto;flex-direction:column;border:1px solid #2b85b7;background:#061827;box-shadow:0 28px 90px rgba(0,0,0,.58)}.modal-page-close{position:absolute;z-index:3;right:14px;top:5px;color:#9edcff;background:transparent;font-size:28px}.modal-shell .state{padding:40px}.modal-shell .hero{flex:none;padding:12px 16px}.modal-shell .hero small{font-size:10px}.modal-shell .hero h1{margin:4px 0;font-size:24px}.modal-shell .hero p{max-width:75%;overflow:hidden;font-size:12px;text-overflow:ellipsis;white-space:nowrap}.modal-shell .hero>strong{font-size:34px}.modal-shell .progress-card{flex:none;margin-top:8px;padding:10px 14px;font-size:13px}.modal-shell .track{height:5px;margin:7px 0}.modal-shell .progress-parts{font-size:11px}.modal-shell .inline-error{margin:5px 0;font-size:11px}.modal-shell .chapter-section{min-height:0;margin-top:10px}.modal-shell .chapter-section h2{margin:0 0 5px;font-size:18px}.modal-shell .chapter-card{grid-template-columns:30px minmax(0,1fr) auto auto;gap:9px;margin-top:5px;padding:7px 10px}.modal-shell .number{width:27px;height:27px;font-size:11px}.modal-shell .chapter-card div{gap:2px}.modal-shell .chapter-card strong{font-size:12px}.modal-shell .chapter-card small,.modal-shell .chapter-card em{font-size:10px}.modal-shell .chapter-card button{padding:6px 11px;font-size:11px}.modal-shell .exam-card{flex:none;margin-top:10px;padding:10px 14px}.modal-shell .exam-card small{font-size:9px}.modal-shell .exam-card h2{margin:3px 0;font-size:16px}.modal-shell .exam-card p{font-size:10px}.modal-shell .exam-card button{padding:7px 12px;font-size:11px}
.modal-backdrop{position:fixed;z-index:90;inset:0;display:grid;place-items:center;padding:20px;background:rgba(0,6,14,.82);backdrop-filter:blur(6px)}.chapter-modal{position:relative;display:flex;box-sizing:border-box;width:75vw;height:75vh;min-width:720px;min-height:520px;max-width:1500px;flex-direction:column;padding:28px;overflow:hidden;border:1px solid #2b85b7;background:#061827;box-shadow:0 28px 90px rgba(0,0,0,.55)}.modal-close{position:absolute;right:20px;top:12px;color:#9edcff;background:transparent;font-size:32px}.modal-header{flex:none;padding-right:45px}.modal-header h2{margin:6px 0;font-size:27px}.modal-body{display:grid;min-height:0;flex:1;grid-template-columns:minmax(0,1.45fr) minmax(280px,.75fr);gap:18px;margin-top:18px}.video-panel,.reading section{border:1px solid rgba(64,174,235,.25);background:#071e31}.video-panel{display:flex;min-height:0;flex-direction:column;padding:14px}.video-panel video{width:100%;min-height:0;flex:1;background:#000}.video-empty{display:grid;min-height:230px;flex:1;place-items:center;color:#7695aa}.video-progress{padding-top:12px}.reading{display:flex;min-height:0;flex-direction:column;gap:12px;overflow:auto}.reading section{padding:16px}.reading h3{margin:0 0 12px}.reading p{white-space:pre-wrap;line-height:1.7}.materials{display:grid;gap:8px}.materials a{display:flex;justify-content:space-between;padding:10px;color:#d8efff;background:#0b2941}.materials a span{color:#4fc3ff}.modal-actions{display:flex;align-items:center;justify-content:flex-end;gap:18px;padding-top:16px}.modal-actions strong{margin-right:auto;color:#66d5ff}.modal-actions small{color:#f5b6a8}.modal-actions button:disabled{opacity:.45}
.modal-page .modal-shell{overscroll-behavior:contain;scrollbar-gutter:stable}.modal-shell .chapter-section{display:grid;min-height:max-content;flex:none;grid-template-columns:minmax(0,1fr);gap:5px}.modal-shell .chapter-section h2{margin:0}.modal-shell .chapter-card{grid-template-columns:27px minmax(0,1fr) auto;gap:7px;margin:0;padding:6px 8px}.modal-shell .chapter-card small{max-width:180px;overflow:hidden;font-size:9px;text-overflow:ellipsis;white-space:nowrap}.modal-shell .chapter-card em{display:none}.modal-shell .chapter-card button{padding:5px 8px;font-size:10px}.modal-page .modal-shell::-webkit-scrollbar{width:8px}.modal-page .modal-shell::-webkit-scrollbar-track{background:#061522}.modal-page .modal-shell::-webkit-scrollbar-thumb{border:2px solid #061522;border-radius:8px;background:#2b85b7}.video-finished{position:absolute;inset:14px 14px 42px;display:grid;z-index:2;place-content:center;gap:18px;background:rgba(5,24,39,.94);text-align:center}.video-finished strong{color:#65d2ff;font-size:20px}.video-finished div{display:flex;gap:12px}.video-finished button,.video-empty button,.quiz-panel button{padding:10px 18px;border:1px solid #39baff;color:#e2f6ff;background:#0d527a}.video-panel{position:relative}.video-empty{gap:18px}.quiz-panel{display:flex;height:100%;box-sizing:border-box;flex-direction:column;padding:24px}.quiz-panel>small{color:#4fc3ff;letter-spacing:.12em}.quiz-panel h3{margin:16px 0;font-size:22px}.quiz-panel textarea{min-height:120px;padding:14px;resize:vertical;color:#e2f2ff;border:1px solid #2a7299;background:#041522}.quiz-panel>button{align-self:flex-end;margin-top:14px}.answer-feedback{margin-top:16px;padding:16px;border:1px solid #2c7399;background:#071827}.answer-feedback.correct strong{color:#65d2a8}.answer-feedback.wrong strong{color:#ff9c9c}.answer-feedback p{margin:10px 0;color:#a8c2d4}.answer-feedback button{float:right}
@media(max-width:900px){.chapter-modal{width:94vw;height:88vh;min-width:0;min-height:0}.modal-body{grid-template-columns:1fr;overflow:auto}.video-panel{min-height:320px}.reading{overflow:visible}}@media(max-width:700px){.modal-page .modal-shell{width:94vw;max-width:94vw;height:88vh;max-height:88vh;overflow:auto}.hero{align-items:start}.hero>strong{font-size:34px}.chapter-card{grid-template-columns:38px 1fr}.chapter-card em,.chapter-card button{grid-column:2}.exam-card{align-items:stretch;flex-direction:column;gap:18px}.chapter-modal{padding:20px}.video-panel{min-height:240px}.video-progress,.modal-actions{align-items:stretch;flex-direction:column}}
</style>
