<script setup>
import { onMounted, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import AppTabBar from '../components/AppTabBar.vue'
import { getFollowers, getFollowing, getUserLikes, getUserPosts, toggleFollowUser } from '../api/forum'
const route=useRoute(),router=useRouter(),posts=ref([]),likes=ref([]),followers=ref([]),following=ref([]),loading=ref(true),error=ref('')
const rows=(v)=>Array.isArray(v)?v:v?.content||v?.records||v?.list||[]
onMounted(async()=>{try{const id=route.params.userId;const [p,l,fr,fg]=await Promise.all([getUserPosts(id,{page:0,size:50}),getUserLikes(id,{page:0,size:30}),getFollowers(id,{page:0,size:30}),getFollowing(id,{page:0,size:30})]);posts.value=rows(p);likes.value=rows(l);followers.value=rows(fr);following.value=rows(fg)}catch(cause){error.value=cause.message}finally{loading.value=false}})
</script>
<template><div class="feature-page"><AppTabBar/><main class="profile-page"><button class="back" @click="router.push('/forum')">‹ 返回论坛</button><div v-if="error" class="feature-error">{{error}}</div><div v-if="loading" class="feature-empty">正在加载个人主页…</div><template v-else><header class="feature-card profile-head"><div class="avatar">{{(posts[0]?.username||'用').slice(0,1)}}</div><div><h1>{{posts[0]?.username||'校园用户'}}</h1><p>{{posts.length}} 篇帖子 · {{followers.length}} 位关注者 · 关注 {{following.length}}</p></div><button class="feature-button feature-button--primary" @click="toggleFollowUser(route.params.userId)">关注</button></header><div class="profile-grid"><section class="feature-card feature-section"><div class="feature-section__head"><h2>发布的帖子</h2></div><div v-if="!posts.length" class="feature-empty">暂无帖子</div><button v-for="post in posts" :key="post.id" class="feature-row profile-post" @click="router.push(`/forum/posts/${post.id}`)"><div class="feature-row__copy"><strong>{{post.title||post.content}}</strong><span>{{post.createTime}} · {{post.commentCount||0}} 评论</span></div></button></section><aside class="feature-card feature-section"><div class="feature-section__head"><h2>获得的点赞</h2><b>{{likes.length}}</b></div><p class="muted">点赞记录来自真实论坛互动。</p></aside></div></template></main></div></template>
<style scoped>
.profile-page{width:min(1000px,calc(100% - 32px));margin:auto;padding:25px 0 48px}.back{margin-bottom:14px;color:#45657f;background:transparent}.profile-head{display:flex;align-items:center;gap:16px;padding:25px}.avatar{display:grid;place-items:center;width:72px;height:72px;border-radius:50%;color:#315f8c;background:#e3edf4;font-size:25px;font-weight:800}.profile-head>div:nth-child(2){flex:1}.profile-head h1{margin:0}.profile-head p{color:#718096}.profile-grid{display:grid;grid-template-columns:2fr 1fr;gap:18px;margin-top:18px}.profile-post{width:100%;text-align:left}@media(max-width:700px){.profile-grid{grid-template-columns:1fr}}
</style>
