<script setup>
import { onMounted, ref } from 'vue'
import { useRoute } from 'vue-router'
import AppTabBar from '../components/AppTabBar.vue'
import { clearSemesterSchedule, deleteScheduleSemester, getSchedulePeriods, getScheduleSettings, updateSchedulePeriods, updateScheduleSettings } from '../api/schedule'

const route=useRoute(),tab=ref(String(route.query.tab||'account')),loading=ref(true),saving=ref(false),error=ref(''),success=ref('')
const settings=ref({jwxStudentId:'',jwxPassword:'',academicYear:'',semesterTerm:1,semesterStart:'',semesters:[]}),periods=ref([])
async function load(){loading.value=true;try{const [s,p]=await Promise.all([getScheduleSettings(),getSchedulePeriods()]);settings.value={...settings.value,...s};periods.value=p||[]}catch(cause){error.value=cause.message}finally{loading.value=false}}
async function saveSettings(){saving.value=true;error.value='';success.value='';try{await updateScheduleSettings({...settings.value,semesterTerm:Number(settings.value.semesterTerm),selected:true});success.value='课表设置已保存';await load()}catch(cause){error.value=cause.message}finally{saving.value=false}}
async function savePeriods(){saving.value=true;try{periods.value=await updateSchedulePeriods({periods:periods.value});success.value='节次时间已保存'}catch(cause){error.value=cause.message}finally{saving.value=false}}
async function removeSemester(item,onlyCourses){try{if(onlyCourses)await clearSemesterSchedule(item.academicYear,item.semesterTerm);else await deleteScheduleSemester(item.academicYear,item.semesterTerm);await load()}catch(cause){error.value=cause.message}}
function changeTab(value){tab.value=value;history.replaceState(null,'',`/mine/schedule-settings?tab=${value}`)}
onMounted(load)
</script>
<template><div class="feature-page"><AppTabBar/><main class="settings-workspace"><header class="feature-heading"><div><h1>课表设置</h1><p>管理教务绑定、学期和节次时间</p></div><a class="feature-button" href="/mine/schedule">返回课表</a></header><div class="feature-tabs settings-tabs"><button :class="{active:tab==='account'}" @click="changeTab('account')">教务账号</button><button :class="{active:tab==='semesters'}" @click="changeTab('semesters')">学期管理</button><button :class="{active:tab==='periods'}" @click="changeTab('periods')">节次时间</button></div><div v-if="error" class="feature-error">{{error}}</div><div v-if="success" class="success">{{success}}</div><div v-if="loading" class="feature-empty">正在加载设置…</div><form v-else-if="tab==='account'" class="feature-card feature-form panel" @submit.prevent="saveSettings"><h2>教务账号与当前学期</h2><label>教务学号<input v-model="settings.jwxStudentId" class="feature-input"/></label><label>教务密码<input v-model="settings.jwxPassword" class="feature-input" type="password"/></label><div class="form-grid"><label>学年<input v-model="settings.academicYear" class="feature-input" placeholder="2025-2026" required/></label><label>学期<select v-model="settings.semesterTerm" class="feature-select"><option :value="1">第一学期</option><option :value="2">第二学期</option></select></label></div><label>学期开始日期<input v-model="settings.semesterStart" class="feature-input" type="date" required/></label><button class="feature-button feature-button--primary" :disabled="saving">保存设置</button></form><section v-else-if="tab==='semesters'" class="feature-card feature-section panel"><div class="feature-section__head"><h2>学期列表</h2></div><div v-if="!settings.semesters?.length" class="feature-empty">保存教务设置后生成学期记录</div><div class="feature-list"><div v-for="item in settings.semesters" :key="`${item.academicYear}-${item.semesterTerm}`" class="feature-row"><div class="feature-row__copy"><strong>{{item.academicYear}} 第 {{item.semesterTerm}} 学期</strong><span>{{item.semesterStart}} · {{item.courseCount||0}} 门课程</span></div><span v-if="item.selected" class="feature-status feature-status--completed">当前学期</span><button class="feature-button" @click="removeSemester(item,true)">清空课程</button><button class="feature-button feature-button--danger" @click="removeSemester(item,false)">删除学期</button></div></div></section><form v-else class="feature-card panel" @submit.prevent="savePeriods"><div class="feature-section__head"><h2>节次时间</h2></div><div class="period-grid"><label v-for="item in periods" :key="item.periodIndex"><strong>第 {{item.periodIndex}} 节</strong><input v-model="item.startTime" class="feature-input" type="time" required/><span>至</span><input v-model="item.endTime" class="feature-input" type="time" required/></label></div><button class="feature-button feature-button--primary" :disabled="saving">保存节次时间</button></form></main></div></template>
<style scoped>
.settings-workspace{width:min(900px,calc(100% - 32px));margin:auto;padding:27px 0 48px}.settings-tabs{width:fit-content;margin-bottom:17px}.panel{padding:24px}.panel h2{margin-top:0}.form-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.success{margin-bottom:13px;padding:12px;border:1px solid #c8e1d5;border-radius:8px;color:#39735d;background:#f1faf6}.period-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-bottom:20px}.period-grid label{display:grid;grid-template-columns:70px 1fr 25px 1fr;align-items:center;gap:7px;padding:11px;border:1px solid #e1e7ed;border-radius:8px}.period-grid span{text-align:center;color:#8291a0}@media(max-width:700px){.period-grid,.form-grid{grid-template-columns:1fr}.period-grid label{grid-template-columns:65px 1fr 20px 1fr}}
</style>
