<script setup>
import { computed, onMounted, ref } from 'vue'
import AppTabBar from '../components/AppTabBar.vue'
import { checkJwxBind, copyScheduleByShareCode, getCurrentSchedule, importScheduleAuto } from '../api/schedule'

const loading=ref(true),error=ref(''),courses=ref([]),week=ref(1),bound=ref(null),showImport=ref(false),importing=ref(false)
const form=ref({mode:'auto',shareCode:'',academicYear:'',semesterTerm:''})
const rows=(value)=>Array.isArray(value)?value:value?.courses||value?.records||value?.list||[]
const weekdays=['周一','周二','周三','周四','周五','周六','周日']
const periods=Array.from({length:12},(_,i)=>i+1)
const courseAt=(day,period)=>courses.value.find((item)=>Number(item.dayOfWeek||item.weekday||item.day)===day&&Number(item.startPeriod||item.period)===period)
async function load(){loading.value=true;try{const [schedule,bind]=await Promise.all([getCurrentSchedule({week:week.value}),checkJwxBind()]);courses.value=rows(schedule);bound.value=bind?.bound??bind?.isBound??false}catch(cause){error.value=cause.message}finally{loading.value=false}}
async function importData(){importing.value=true;try{if(form.value.mode==='share')await copyScheduleByShareCode(form.value.shareCode,form.value);else await importScheduleAuto({academicYear:form.value.academicYear,semesterTerm:form.value.semesterTerm});showImport.value=false;await load()}catch(cause){error.value=cause.message}finally{importing.value=false}}
onMounted(load)
</script>
<template><div class="feature-page"><AppTabBar/><main class="schedule-page"><header class="feature-heading"><div><h1>我的课表</h1><p>真实课表数据 · 第 {{week}} 周</p></div><div class="feature-actions"><select v-model="week" class="feature-select week-select" @change="load"><option v-for="value in 20" :key="value" :value="value">第 {{value}} 周</option></select><button class="feature-button feature-button--primary" @click="showImport=true">导入课表</button></div></header><div v-if="error" class="feature-error">{{error}}</div><div class="bind-note" :class="{bound}"><span>{{bound?'教务账号已绑定':'尚未绑定教务账号'}}</span><a href="/mine/edu-account">教务设置</a></div><div v-if="loading" class="feature-empty">正在加载课表…</div><div v-else class="feature-card timetable"><div class="time-head">节次</div><div v-for="day in weekdays" :key="day" class="day-head">{{day}}</div><template v-for="period in periods" :key="period"><div class="period">{{period}}</div><div v-for="day in 7" :key="`${day}-${period}`" class="cell"><article v-if="courseAt(day,period)"><strong>{{courseAt(day,period).courseName||courseAt(day,period).name}}</strong><span>{{courseAt(day,period).classroom||courseAt(day,period).location}}</span><small>{{courseAt(day,period).teacherName||courseAt(day,period).teacher}}</small></article></div></template></div><div v-if="!courses.length&&!loading" class="feature-empty no-courses">当前周暂无课程数据，可从教务系统或分享码导入。</div></main><div v-if="showImport" class="feature-modal-mask" @click.self="showImport=false"><form class="feature-modal feature-form" @submit.prevent="importData"><div class="feature-modal__head"><h2>导入课表</h2><button type="button" class="feature-modal__close" @click="showImport=false">×</button></div><div class="feature-tabs"><button type="button" :class="{active:form.mode==='auto'}" @click="form.mode='auto'">教务自动导入</button><button type="button" :class="{active:form.mode==='share'}" @click="form.mode='share'">分享码复制</button></div><label>学年<input v-model="form.academicYear" class="feature-input" placeholder="例如 2025-2026" required/></label><label>学期<input v-model="form.semesterTerm" class="feature-input" placeholder="例如 2" required/></label><label v-if="form.mode==='share'">分享码<input v-model="form.shareCode" class="feature-input" required/></label><button class="feature-button feature-button--primary" :disabled="importing">{{importing?'导入中…':'开始导入'}}</button></form></div></div></template>
<style scoped>
.schedule-page{width:min(1400px,calc(100% - 32px));margin:auto;padding:26px 0 45px}.week-select{width:130px}.bind-note{display:flex;justify-content:space-between;margin-bottom:15px;padding:11px 14px;border:1px solid #ead5b1;border-radius:8px;color:#8a642d;background:#fffaf0}.bind-note.bound{border-color:#c8e1d5;color:#39735d;background:#f1faf6}.bind-note a{color:inherit;font-weight:700}.timetable{display:grid;grid-template-columns:72px repeat(7,minmax(120px,1fr));overflow:auto}.time-head,.day-head,.period,.cell{min-height:62px;border-right:1px solid #e6ebf0;border-bottom:1px solid #e6ebf0}.time-head,.day-head,.period{display:grid;place-items:center;color:#607286;background:#f7f9fb;font-weight:700}.day-head{min-height:48px}.cell{padding:5px;background:#fff}.cell article{height:100%;min-height:70px;padding:8px;border-left:3px solid #527797;border-radius:6px;background:#edf4f8}.cell strong,.cell span,.cell small{display:block}.cell strong{color:#29455f;font-size:12px}.cell span,.cell small{margin-top:4px;color:#6f8091;font-size:10px}.no-courses{margin-top:16px}
</style>
